packages:
  - "packages/*"

onlyBuiltDependencies:
  - "@swc/core"
  - "@duckdb/node-bindings"
  - esbuild
  - cbor-extract

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
  - "@nestjs/core"

allowBuilds:
  esbuild: set this to true or false
  lz4: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false

minimumReleaseAgeExclude:
  - '@malloydata/db-bigquery@0.0.414'
  - '@malloydata/db-databricks@0.0.414'
  - '@malloydata/db-duckdb@0.0.414'
  - '@malloydata/db-mysql@0.0.414'
  - '@malloydata/db-postgres@0.0.414'
  - '@malloydata/db-snowflake@0.0.414'
  - '@malloydata/db-trino@0.0.414'
  - '@malloydata/malloy-connections@0.0.414'
  - '@malloydata/malloy-filter@0.0.414'
  - '@malloydata/malloy-interfaces@0.0.414'
  - '@malloydata/malloy-tag@0.0.414'
  - '@malloydata/malloy@0.0.414'
  - '@malloydata/render@0.0.414'
