-- A REPO BECOMES A THING.
--
-- Generated by drizzle-kit, then reordered by hand so the BACKFILL sits between
-- the DDL that creates the new shape and the constraints that depend on it.
-- Reviewed for one property above all: this migration must not be able to fail
-- on data it did not choose. Every unique index it creates is implied either by
-- an index that already exists or by its own backfill -- noted at each one.
--
-- The old dataset columns (`github_repo`, `github_branch`, `github_use_token`)
-- are deliberately NOT dropped here. 0027 does that, as a separate entry, so a
-- deployment can ship this one, promote the code that stopped reading them, and
-- only then drop -- the ordering CLAUDE.md calls for, since a Vercel build
-- migrates BEFORE the new code is promoted.

CREATE TYPE "public"."repo_revision_source" AS ENUM('cli', 'github');--> statement-breakpoint
CREATE TABLE "repos" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"slug" text NOT NULL,
	"title" text,
	"owner_id" uuid NOT NULL,
	"github_repo" text,
	"github_branch" text,
	"github_use_token" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "repo_revisions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"repo_id" uuid NOT NULL,
	"revision" integer NOT NULL,
	"source" "repo_revision_source" NOT NULL,
	"created_by_id" uuid,
	"git_sha" text,
	"git_branch" text,
	"git_dirty" boolean,
	"archive" "bytea" NOT NULL,
	"archive_bytes" integer NOT NULL,
	"archive_sha256" text NOT NULL,
	"datasets" jsonb,
	"has_devcontainer" boolean DEFAULT false NOT NULL,
	"verified_at" timestamp with time zone,
	"verify_error" text,
	"active" boolean DEFAULT false NOT NULL,
	"activated_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "dataset_aliases" (
	"alias" text PRIMARY KEY NOT NULL,
	"dataset_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "repos" ADD CONSTRAINT "repos_owner_id_users_id_fk" FOREIGN KEY ("owner_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "repo_revisions" ADD CONSTRAINT "repo_revisions_repo_id_repos_id_fk" FOREIGN KEY ("repo_id") REFERENCES "public"."repos"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "repo_revisions" ADD CONSTRAINT "repo_revisions_created_by_id_users_id_fk" FOREIGN KEY ("created_by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dataset_aliases" ADD CONSTRAINT "dataset_aliases_dataset_id_datasets_id_fk" FOREIGN KEY ("dataset_id") REFERENCES "public"."datasets"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "datasets" ADD COLUMN "repo_id" uuid;--> statement-breakpoint
ALTER TABLE "datasets" ADD CONSTRAINT "datasets_repo_id_repos_id_fk" FOREIGN KEY ("repo_id") REFERENCES "public"."repos"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "malloy_models" ADD COLUMN "revision_id" uuid;--> statement-breakpoint
ALTER TABLE "malloy_models" ADD CONSTRAINT "malloy_models_revision_id_repo_revisions_id_fk" FOREIGN KEY ("revision_id") REFERENCES "public"."repo_revisions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "malloy_models" ADD COLUMN "active" boolean DEFAULT false NOT NULL;--> statement-breakpoint
-- -- BACKFILL ------------------------------------------------------------------
-- One repo per DISTINCT (github_repo, github_branch) pair that any dataset row
-- names - exactly the set the old code treated as a repo, so nothing is
-- invented and nothing is lost.
--
-- Three per-repo facts have to be chosen from rows that may disagree, and each
-- is chosen DETERMINISTICALLY. The old code chose with `rows[0]` on a query with
-- no ORDER BY, which is how `github_use_token` became an intermittent failure
-- that flipped with row order.
--
--   owner - the owner of the oldest LIVE row, else of the oldest row. The
--           person whose dataset is actually serving is the one who publishes.
--   token - bool_or. One production repo had three rows with two values. A
--           token sent where it is not needed is read by GitHub and ignored; a
--           token NOT sent to a private repo is a 404 and a dead dataset. The
--           failure modes are not symmetric, so prefer sending.
--   slug  - the repo NAME, slugified the way a dataset name is. A second repo
--           whose name slugifies the same gets `_2`: a name nobody chose, and
--           the only alternative that cannot fail. Renameable afterwards.
WITH pairs AS (
	SELECT
		d.github_repo AS github_repo,
		COALESCE(NULLIF(btrim(d.github_branch), ''), 'main') AS github_branch,
		bool_or(d.github_use_token) AS github_use_token,
		min(d.created_at) AS created_at,
		(ARRAY_AGG(d.user_id ORDER BY (d.status = 'ready') DESC, d.created_at ASC, d.id ASC))[1] AS owner_id
	FROM datasets d
	WHERE d.github_repo IS NOT NULL AND btrim(d.github_repo) <> ''
	GROUP BY 1, 2
), named AS (
	-- The last path segment of whatever is stored. The three spellings
	-- parseGitHubRepo accepted - a bare owner/name, an https URL, and an ssh
	-- remote - all reduce to the same leaf.
	SELECT p.*, regexp_replace(regexp_replace(btrim(p.github_repo), '\.git$', ''), '^.*[/:]', '') AS leaf
	FROM pairs p
), slugged AS (
	SELECT n.*,
		COALESCE(
			NULLIF(left(btrim(regexp_replace(lower(n.leaf), '[^a-z0-9]+', '_', 'g'), '_'), 48), ''),
			'repo'
		) AS base
	FROM named n
), numbered AS (
	SELECT s.*, row_number() OVER (PARTITION BY s.base ORDER BY s.github_repo, s.github_branch) AS rn
	FROM slugged s
)
INSERT INTO repos (slug, owner_id, github_repo, github_branch, github_use_token, created_at, updated_at)
SELECT
	CASE WHEN rn = 1 THEN base ELSE base || '_' || rn END,
	owner_id, github_repo, github_branch, github_use_token, created_at, now()
FROM numbered;--> statement-breakpoint
-- Membership stops being a text match and becomes a foreign key. The branch
-- coalesce mirrors what the old code did at read time (`githubBranch ?? main`),
-- so a row whose branch was never set lands in the repo it was always refreshed
-- as part of.
UPDATE datasets d
SET repo_id = r.id
FROM repos r
WHERE d.github_repo = r.github_repo
	AND COALESCE(NULLIF(btrim(d.github_branch), ''), 'main') = r.github_branch;--> statement-breakpoint
-- '' is the repo root. NULL was, and a nullable column cannot be constrained by
-- a partial unique index - two (repo_id, NULL) rows do not conflict in Postgres.
UPDATE datasets SET repo_dir = COALESCE(btrim(repo_dir, '/'), '');--> statement-breakpoint
ALTER TABLE "datasets" ALTER COLUMN "repo_dir" SET DEFAULT '';--> statement-breakpoint
ALTER TABLE "datasets" ALTER COLUMN "repo_dir" SET NOT NULL;--> statement-breakpoint
-- EVERY NAME IN THE WILD, PINNED.
--
-- A repo-backed dataset's public name becomes <repo>:<name>, and the bare name
-- is what share links, saved MCP client configs, `--dataset <name>` invocations
-- and committed malloy-config.json targets already say. The alias freezes which
-- dataset each of those meant, so the day a second repo publishes its own
-- `sales` the old links keep resolving instead of becoming ambiguous.
--
-- Only repo-backed, live datasets: a repo-less dataset's bare name is still its
-- own identity, so an alias for it would be a second copy of the same fact that
-- could then drift. ON CONFLICT is belt-and-braces - the index being dropped
-- below made a clash impossible - and costs nothing.
INSERT INTO dataset_aliases (alias, dataset_id)
SELECT d.name, d.id
FROM datasets d
WHERE d.repo_id IS NOT NULL AND d.status = 'ready'
ON CONFLICT (alias) DO NOTHING;--> statement-breakpoint
-- WHICH MODEL EACH DATASET SERVES, said rather than guessed.
--
-- The reads this replaces were ORDER BY created_at DESC LIMIT 1, which ties when
-- two versions land in the same millisecond and then returns whichever row
-- Postgres felt like. `version` is monotonic per dataset, so it leads the order
-- here and created_at only breaks ties - which is also the answer those reads
-- would have given on every row that was not tied.
WITH latest AS (
	SELECT DISTINCT ON (dataset_id) id
	FROM malloy_models
	ORDER BY dataset_id, version DESC, created_at DESC, id
)
UPDATE malloy_models SET active = true WHERE id IN (SELECT id FROM latest);--> statement-breakpoint
-- -- CONSTRAINTS THAT DEPEND ON THE BACKFILL -----------------------------------
-- The global name index goes; names are scoped to a repo now. Dropping an index
-- only relaxes, so it is safe while the previous code is still live.
DROP INDEX "datasets_name_ready_unique";--> statement-breakpoint
CREATE INDEX "datasets_repo_idx" ON "datasets" USING btree ("repo_id");--> statement-breakpoint
CREATE INDEX "datasets_repo_dir_idx" ON "datasets" USING btree ("repo_id","repo_dir");--> statement-breakpoint
-- Implied by the index just dropped: two live datasets could not share a name
-- at all, so they cannot share one within a repo.
CREATE UNIQUE INDEX "datasets_repo_name_ready_unique" ON "datasets" USING btree ("repo_id","name") WHERE status = 'ready' and repo_id is not null;--> statement-breakpoint
-- A strict subset of the index just dropped.
CREATE UNIQUE INDEX "datasets_unscoped_name_ready_unique" ON "datasets" USING btree ("name") WHERE status = 'ready' and repo_id is null;--> statement-breakpoint
CREATE INDEX "malloy_models_revision_idx" ON "malloy_models" USING btree ("revision_id");--> statement-breakpoint
-- Implied by the backfill above: DISTINCT ON sets at most one row per dataset.
CREATE UNIQUE INDEX "malloy_models_one_active" ON "malloy_models" USING btree ("dataset_id") WHERE active;--> statement-breakpoint
CREATE INDEX "dataset_aliases_dataset_idx" ON "dataset_aliases" USING btree ("dataset_id");--> statement-breakpoint
-- Implied by the `rn` disambiguation in the backfill.
CREATE UNIQUE INDEX "repos_slug_unique" ON "repos" USING btree ("slug");--> statement-breakpoint
-- Implied by the GROUP BY that built the rows.
CREATE UNIQUE INDEX "repos_github_unique" ON "repos" USING btree ("github_repo","github_branch") WHERE github_repo is not null;--> statement-breakpoint
CREATE INDEX "repos_owner_idx" ON "repos" USING btree ("owner_id");--> statement-breakpoint
CREATE UNIQUE INDEX "repo_revisions_repo_revision_unique" ON "repo_revisions" USING btree ("repo_id","revision");--> statement-breakpoint
CREATE UNIQUE INDEX "repo_revisions_one_active" ON "repo_revisions" USING btree ("repo_id") WHERE active;--> statement-breakpoint
CREATE INDEX "repo_revisions_repo_created_idx" ON "repo_revisions" USING btree ("repo_id","created_at");
