// Generates src/content/generated.ts so the published package carries its
// model-facing text as compiled-in strings — no runtime file reads (and
// therefore no serverless file-tracing exposure). Two sources, one pipeline:
//   • content/*.md          → contentFiles map (the yo_help language topics)
//   • content/prompts/**.md → prompts tree     (tool titles/descriptions +
//                             server instructions; the audit/edit surface)
import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const here = path.dirname(url.fileURLToPath(import.meta.url));
const contentDir = path.join(here, '..', 'content');
const helpDir = path.join(contentDir, 'help');
const promptsDir = path.join(contentDir, 'prompts');
const outFile = path.join(here, '..', 'src', 'content', 'generated.ts');

// Help-topic content lives under content/help/**, namespaced by directory:
// content/help/explore/how-to.md → key "explore/how-to.md".
// The directory layout IS the topic namespace; help.ts derives each topic's
// name from the key (slug = the path). A new category is just a new directory
// — it appears with no code change. README.md (author docs) lives in content/,
// outside help/, so it is never shipped. Keys are POSIX-style ('/').
const files: Record<string, string> = {};
function collectHelp(dir: string, prefix: string): void {
  for (const name of fs.readdirSync(dir).sort()) {
    const full = path.join(dir, name);
    if (fs.statSync(full).isDirectory()) collectHelp(full, prefix + name + '/');
    else if (name.endsWith('.md')) files[prefix + name] = fs.readFileSync(full, 'utf8');
  }
}
if (fs.existsSync(helpDir)) collectHelp(helpDir, '');

// Nested prompt tree (content/prompts/**.md). Each directory is a key; each
// .md file is a leaf keyed by its basename, value = its trimmed text. Emitted
// `as const` so consumers get literal types and a typo'd key is a compile error.
type Tree = { [k: string]: Tree | string };
function walk(dir: string): Tree {
  const node: Tree = {};
  for (const name of fs.readdirSync(dir).sort()) {
    const full = path.join(dir, name);
    if (fs.statSync(full).isDirectory()) node[name] = walk(full);
    else if (name.endsWith('.md')) {
      node[name.slice(0, -3)] = fs.readFileSync(full, 'utf8').trim();
    }
  }
  return node;
}
const prompts: Tree = fs.existsSync(promptsDir) ? walk(promptsDir) : {};

const body =
  '// GENERATED by scripts/embed-content.ts — do not edit.\n' +
  '// Sources: content/*.md (yo_help topics), content/prompts/**.md (prompt surfaces).\n' +
  'export const contentFiles: Record<string, string> = ' +
  JSON.stringify(files, null, 2) +
  ';\n\n' +
  'export const prompts = ' +
  JSON.stringify(prompts, null, 2) +
  ' as const;\n';

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, body);

function leaves(t: Tree): number {
  return Object.values(t).reduce<number>(
    (n, v) => n + (typeof v === 'string' ? 1 : leaves(v)),
    0,
  );
}

// Guard the lesson learned the hard way: Claude Code truncates a server's
// instructions at ~2KB. The engine's own contribution per surface (core +
// surface block) must stay well under that — hosts append policy on top.
const CAP = 2048;
const core = typeof prompts.core === 'object' ? (prompts.core as Tree) : {};
const bytes = (s: unknown) => (typeof s === 'string' ? Buffer.byteLength(s) : 0);
for (const surface of ['develop', 'explore'] as const) {
  const node = prompts[surface];
  if (typeof node !== 'object') continue;
  const size = bytes((node as Tree).instructions) + bytes(core.instructions) + 2; // '\n\n'
  console.log(`  ${surface} instructions: ${size}B${size > CAP ? '  ⚠️ OVER 2KB CAP' : ''}`);
}

console.log(
  `embedded ${Object.keys(files).length} content files + ${leaves(prompts)} prompts → ${path.relative(process.cwd(), outFile)}`,
);
