// Generates src/content/generated.ts so the published package carries its
// model-facing text as compiled-in strings — no runtime file reads (and
// therefore no serverless file-tracing exposure). Two sources, one pipeline:
//   • content/*.md          → contentFiles map (the yo_help language topics)
//   • content/prompts/**.md → prompts tree     (tool titles/descriptions +
//                             server instructions; the audit/edit surface)
import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const here = path.dirname(url.fileURLToPath(import.meta.url));
const contentDir = path.join(here, '..', 'content');
const promptsDir = path.join(contentDir, 'prompts');
const outFile = path.join(here, '..', 'src', 'content', 'generated.ts');

// Flat help-topic content (top-level content/*.md). The `prompts` subdir is
// skipped here (not a .md file) and handled as a tree below.
const files: Record<string, string> = {};
for (const name of fs.readdirSync(contentDir).sort()) {
  if (!name.endsWith('.md')) continue;
  if (name === 'README.md') continue; // docs for authors, not shippable content
  files[name] = fs.readFileSync(path.join(contentDir, name), 'utf8');
}

// Nested prompt tree (content/prompts/**.md). Each directory is a key; each
// .md file is a leaf keyed by its basename, value = its trimmed text. Emitted
// `as const` so consumers get literal types and a typo'd key is a compile error.
type Tree = { [k: string]: Tree | string };
function walk(dir: string): Tree {
  const node: Tree = {};
  for (const name of fs.readdirSync(dir).sort()) {
    const full = path.join(dir, name);
    if (fs.statSync(full).isDirectory()) node[name] = walk(full);
    else if (name.endsWith('.md')) {
      node[name.slice(0, -3)] = fs.readFileSync(full, 'utf8').trim();
    }
  }
  return node;
}
const prompts: Tree = fs.existsSync(promptsDir) ? walk(promptsDir) : {};

const body =
  '// GENERATED by scripts/embed-content.ts — do not edit.\n' +
  '// Sources: content/*.md (yo_help topics), content/prompts/**.md (prompt surfaces).\n' +
  'export const contentFiles: Record<string, string> = ' +
  JSON.stringify(files, null, 2) +
  ';\n\n' +
  'export const prompts = ' +
  JSON.stringify(prompts, null, 2) +
  ' as const;\n';

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, body);

function leaves(t: Tree): number {
  return Object.values(t).reduce<number>(
    (n, v) => n + (typeof v === 'string' ? 1 : leaves(v)),
    0,
  );
}

// Guard the lesson learned the hard way: Claude Code truncates a server's
// instructions at ~2KB. The engine's own contribution per surface (core +
// surface block) must stay well under that — hosts append policy on top.
const CAP = 2048;
const core = typeof prompts.core === 'object' ? (prompts.core as Tree) : {};
const bytes = (s: unknown) => (typeof s === 'string' ? Buffer.byteLength(s) : 0);
for (const surface of ['develop', 'explore'] as const) {
  const node = prompts[surface];
  if (typeof node !== 'object') continue;
  const size = bytes((node as Tree).instructions) + bytes(core.instructions) + 2; // '\n\n'
  console.log(`  ${surface} instructions: ${size}B${size > CAP ? '  ⚠️ OVER 2KB CAP' : ''}`);
}

console.log(
  `embedded ${Object.keys(files).length} content files + ${leaves(prompts)} prompts → ${path.relative(process.cwd(), outFile)}`,
);
