// `malloyyo init` — make a model repo "just work" when you fire off Claude:
//   1. Write .mcp.json so `cd <repo> && claude` connects the AUTHOR server
//      (malloyyo mcp --develop) — named `malloyyo_author`, so the mode shows in
//      every tool prefix (mcp__malloyyo_author__…) and can't be confused with
//      the core malloy-cli.
//   2. Scaffold index.malloy (the entry model the dashboard/publish tooling
//      requires) if it's missing, re-exporting the repo's models — so the
//      "No index.malloy" landmine doesn't hit every authoring session.
//
// The .mcp.json is the guaranteed fix; the index.malloy is a best-effort
// scaffold to review (validate it with `malloyyo mcp --develop` / `dashboard
// dev`).

import fs from "node:fs";
import path from "node:path";

const AUTHOR_MCP = {
  mcpServers: {
    // No -C: the server roots at the launch cwd (the project dir), so this file
    // is portable/committable — no absolute paths baked in.
    malloyyo_author: { command: "malloyyo", args: ["mcp", "--develop"] },
  },
};

/** Top-level exportable names in a .malloy file: sources, queries, and givens.
    Heuristic (no compile) — good enough to scaffold; the author reviews it. */
function exportableNames(src: string): string[] {
  const names = new Set<string>();
  // Strip line comments so `// query: foo` etc. don't match.
  const code = src.replace(/\/\/[^\n]*/g, "");
  for (const m of code.matchAll(/^\s*(?:source|query)\s*:\s*([A-Za-z_]\w*)\s+is\b/gm)) {
    names.add(m[1]);
  }
  // givens: `NAME :: filter<…> is …` (the `::` type annotation is distinctive).
  for (const m of code.matchAll(/^\s*([A-Za-z_]\w*)\s*::/gm)) {
    names.add(m[1]);
  }
  return [...names];
}

function scaffoldIndex(root: string): { wrote: boolean; note: string } {
  const indexPath = path.join(root, "index.malloy");
  if (fs.existsSync(indexPath)) {
    return { wrote: false, note: "index.malloy already exists — left as-is" };
  }
  const models = fs
    .readdirSync(root)
    .filter((f) => f.endsWith(".malloy") && f !== "index.malloy")
    .sort();
  if (models.length === 0) {
    return { wrote: false, note: "no .malloy files found — skipped index.malloy" };
  }
  const blocks: string[] = [
    "// Generated by `malloyyo init` — the entry model. `dashboard dev`, `lint`,",
    "// `malloyyo test`, and the hosted app only see what THIS file exports.",
    "// Review the re-exports below (add givens / suggest queries your dashboards",
    "// reference), then validate with `malloyyo mcp --develop` or `dashboard dev`.",
    "",
  ];
  let anyNames = false;
  for (const file of models) {
    const names = exportableNames(fs.readFileSync(path.join(root, file), "utf8"));
    if (names.length === 0) {
      blocks.push(`// ${file}: no top-level source/query/given detected — add exports by hand`);
      continue;
    }
    anyNames = true;
    const list = names.join(", ");
    blocks.push(`import { ${list} } from './${file}'`);
    blocks.push(`export { ${list} }`);
    blocks.push("");
  }
  fs.writeFileSync(indexPath, blocks.join("\n") + "\n");
  return {
    wrote: true,
    note: anyNames
      ? `wrote index.malloy re-exporting ${models.length} model file(s) — REVIEW it`
      : "wrote index.malloy skeleton — no exports detected, fill them in by hand",
  };
}

export async function initCmd(dir: string): Promise<void> {
  const root = path.resolve(dir);
  if (!fs.existsSync(root) || !fs.statSync(root).isDirectory()) {
    throw new Error(`not a directory: ${root}`);
  }

  const mcpPath = path.join(root, ".mcp.json");
  if (fs.existsSync(mcpPath)) {
    // Don't clobber a hand-tuned config; report what a fresh one would be.
    console.log(`• .mcp.json exists — leaving it. For author-by-default it should be:`);
    console.log(`    ${JSON.stringify(AUTHOR_MCP.mcpServers.malloyyo_author)}`);
    console.log(`  (server key "malloyyo_author", command "malloyyo mcp --develop").`);
  } else {
    fs.writeFileSync(mcpPath, JSON.stringify(AUTHOR_MCP, null, 2) + "\n");
    console.log(`✓ wrote .mcp.json — \`cd ${dir} && claude\` now opens in AUTHOR mode`);
  }

  const idx = scaffoldIndex(root);
  console.log(`${idx.wrote ? "✓" : "•"} ${idx.note}`);

  console.log("");
  console.log("Next:");
  console.log("  claude              # author mode (mcp__malloyyo_author__* tools)");
  console.log("  malloyyo test       # preview exactly what claude.ai web will see");
  console.log("  malloyyo dashboard dev   # see dashboards render in a browser");
}
